const ROLES = {
  SUPER_ADMIN: "SUPER_ADMIN",
  BOSS: "BOSS",
  GERANT: "GERANT",
  CLIENT: "CLIENT",
  LOCATAIRE: "LOCATAIRE",
};

const ADMIN_ROLES = [ROLES.SUPER_ADMIN, ROLES.BOSS, ROLES.GERANT];

const STATUT_PARCELLE = {
  DISPONIBLE: "DISPONIBLE",
  RESERVEE: "RESERVEE",
  VENDUE: "VENDUE",
  MAINTENANCE: "MAINTENANCE",
  MASQUEE: "MASQUEE",
  ARCHIVEE: "ARCHIVEE",
};

const STATUT_RESERVATION = {
  EN_ATTENTE: "EN_ATTENTE",
  EN_COURS: "EN_COURS",
  CONFIRMEE: "CONFIRMEE",
  EXPIREE: "EXPIREE",
  ANNULEE: "ANNULEE",
  TRANSFORMEE_EN_VENTE: "TRANSFORMEE_EN_VENTE",
};

const STATUT_VENTE = {
  EN_COURS: "EN_COURS",
  COMPLETE: "COMPLETE",
  ANNULEE: "ANNULEE",
};

const STATUT_FACTURE = {
  EN_ATTENTE: "EN_ATTENTE",
  VALIDEE: "VALIDEE",
  REJETEE: "REJETEE",
};

const STATUT_PAIEMENT_LOYER = {
  EN_ATTENTE: "EN_ATTENTE",
  VALIDE: "VALIDE",
  REJETE: "REJETE",
};

const TYPE_PARCELLE = {
  RESIDENTIELLE: "RESIDENTIELLE",
  COMMERCIALE: "COMMERCIALE",
  AGRICOLE: "AGRICOLE",
  INDUSTRIELLE: "INDUSTRIELLE",
  AUTRE: "AUTRE",
};

const CATEGORIE_LOCATAIRE = {
  SIMPLE: "SIMPLE",
  ENTREPRISE: "ENTREPRISE",
};

const DEVISE = { USD: "USD", CDF: "CDF" };

const MODULE = {
  PARCELLES: "PARCELLES",
  KBS: "KBS",
  SYSTEME: "SYSTEME",
  GENERAL: "GENERAL",
};

const CANAL_NOTIF = { APP: "APP", EMAIL: "EMAIL", SMS: "SMS", PUSH: "PUSH" };

module.exports = {
  ROLES,
  ADMIN_ROLES,
  STATUT_PARCELLE,
  STATUT_RESERVATION,
  STATUT_VENTE,
  STATUT_FACTURE,
  STATUT_PAIEMENT_LOYER,
  TYPE_PARCELLE,
  CATEGORIE_LOCATAIRE,
  DEVISE,
  MODULE,
  CANAL_NOTIF,
};